events/urls.py
from django.urls import path
from events.views import *

app_name = 'events'

urlpatterns = [
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),

    ##homepage
    path('', HomePageView.as_view(), name="home"),

    ##Evetn Create/Update
    path('create/', EventCreate.as_view(), name="event_create"),
    path('update/<int:pk>', EventUpdate.as_view(), name="event_update"),

]

myriad/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path ('', include('events.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

events/models.py
from multiprocessing.synchronize import Event
import datetime
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class DateTimeModel(models.Model):
	created_at = models.DateTimeField(
		auto_now_add=True, auto_now=False, null=True, blank=True)
	updated_at = models.DateTimeField(
		auto_now_add=False, auto_now=True, null=True, blank=True)
	deleted_at = models.DateTimeField(null=True, blank=True)

	class Meta:
		abstract = True


class UserModel(DateTimeModel):
	created_by = models.ForeignKey(User,null=True,on_delete=models.SET_NULL)

	class Meta:
		abstract = True

class Event(UserModel):
    event_name = models.CharField(max_length=100, null = True, blank =True)
    description = models.TextField(max_length=4000, null=True, blank=True)
    date_time = models.DateTimeField(default = datetime.datetime.now,null=True,blank=True)
    venue = models.CharField(max_length= 100, null = True, blank = True)
    venue_url = models.URLField(null=True, blank = True)
    signup_form_code =  models.TextField (max_length=500, null=True, blank=True)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.event_name

events/forms.py
from django import forms
from django.forms import ModelForm, Select, TextInput
from events.models import *



class LoginForm(forms.Form):
  	username = forms.CharField(
  		widget=forms.TextInput(
  			attrs={'class': 'form-control'}))
  	password = forms.CharField(
  		widget=forms.PasswordInput(
  			attrs={'class': 'form-control'}))

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['event_name', 'description', 'date_time', 'venue', 'venue_url','signup_form_code']
        labels = {
            "event_name": "",
            "description": "",
            'date_time':"",
             "venue":"",
             "venue_url":"",
             "signup_form_code":""
        }

    def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['event_name'].widget.attrs['placeholder'] = 'Event Name'
       self.fields['description'].widget.attrs['placeholder'] = 'Description'
       self.fields['date_time'].widget.attrs['placeholder'] = 'Date Time'
       self.fields['venue'].widget.attrs['placeholder'] = 'Venue'
       self.fields['venue'].widget.attrs['id'] = 'autocomplete'
       self.fields['venue_url'].widget.attrs['placeholder'] = 'Venue URL'
       self.fields['signup_form_code'].widget.attrs['placeholder'] = 'Eloqua Signup Form Code'
       for field in iter(self.fields):
           self.fields[field].widget.attrs.update({
               'class': 'form-control'
           })
           

events/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, View,UpdateView, CreateView, DeleteView,View
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from braces.views import SuperuserRequiredMixin, LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.messages.views import SuccessMessageMixin
from bootstrap_modal_forms.mixins import PassRequestMixin
from django.shortcuts import redirect


from events.forms import *
from events.models import *
# Create your views here.

class AuthMixin(LoginRequiredMixin):
    login_url = reverse_lazy('events:login')


class Login(TemplateView):
    template_name = "login.html"

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            form = LoginForm()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
            else:
                return render(request, self.template_name, {
                    'form': form, 'user': username, 'error': 'Incorrect username or password'})

class Logout(AuthMixin, View):
    def get(self, request):
        logout(self.request)
        return redirect('events:login')

##Mixins
class CreateMixin(AuthMixin, CreateView):
    def form_valid(self, form):
        creater = User.objects.get(username=self.request.user)
        form.instance.created_by = creater
        obj = form.save()
        return super(CreateMixin, self).form_valid(form)


class UpdateMixin(AuthMixin, UpdateView):
    def form_valid(self, form):
        prev_obj = self.get_object()
        obj = form.save()
        return super(UpdateMixin, self).form_valid(form)


##home
class HomePageView(AuthMixin,ListView):
    template_name = 'home/index.html'
    model = Event
    paginate_by = 8


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_name'] = 'home'
        return context

##event CRUD
class EventCreate(CreateMixin,PassRequestMixin, SuccessMessageMixin,):
    template_name = 'home/event_form.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('events:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_name'] = 'event_create'
        return context


class EventUpdate(UpdateMixin):
    template_name = 'home/event_form.html'
    model = Event
    form_class = EventForm
    success_url = reverse_lazy('events:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['url_name'] = 'event_update'
        return context

templates/home/event_form.html
<form method="post" action="" novalidate >
        {% csrf_token %}
      
       <div class="modal-header bg-primary text-white">
           {%if object%}
          <h5 class="modal-title">Update Event</h5>
          {%else%}
          <h5 class="modal-title">Create Event</h5>

          {%endif%}
          <button style="color:white" type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      
        <div class="modal-body">
          {% for field in form %}
            <div class="form-group{% if field.errors %} invalid{% endif %}">
              <label for="{{ field.id_for_label }}"></label>
              {{ field }}
              {% for error in field.errors %}
                <p class="help-block">{{ error }}</p>
              {% endfor %}
            </div>

          {% endfor %}
        </div>
            
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-success">Save</button>
        </div>
    </div>
      
      </form>
     

templates/home/index.html
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Events</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
        crossorigin="anonymous"> <!-- Google fonts - Popppins for copy-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
    <div id="root" class=" container-fluid  h-100">
        <div class="row">
            <nav class="navbar navbar-dark bg-dark w-100">
                <a class="navbar-brand" href="{% url 'events:home' %}">[[brand]]</a>
                <a class="btn ml-auto text-white" href="{% url 'events:logout'%}">Logout</a>
            </nav>
        </div>

        <div class="row main-row">
            <div class="col-md-2 bg-primary">
                <div class="row mt-3 ml-1">
                    <p style="color:white">Events +</p>
                </div>
            </div>
            <div class="col-md-10 mt-2 justify-content-center">

                {% block main_content %}
                <div class="row mb-3">
                    <div class="col-md-3">
                        <div class="modal fade" tabindex="-1" role="dialog" id="modal">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">

                                </div>
                            </div>
                        </div>

                        <!-- Create book button -->
                        <button class="create-book btn btn-primary" type="button" name="button">Create</button>
                    </div>
                </div>
                <div class="row">
                    {%for event in object_list%}

                    <div class="col-md-3 mb-3 animated bounceIn">
                        <div class="card custom-shadow">
                            <div class="card-header">
                                <p style="font-weight:bold">
                                    {{event.event_name}}
                                </p>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">{{event.date_time}}</h5>
                                <p class="card-text">{{event.venue}}</p>

                                <div class="row justify-content-end">
                                    <a data-id="{% url 'events:event_update' event.id %}" class="update-book btn text-right text-primary">More
                                        +</a>
                                </div>
                            </div>
                        </div>
                    </div>

                    {%endfor%}

                </div>
                <div class="row">
                    <div class="col-md-10">
                        {% if is_paginated %}
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
                            {% else %}
                            <li class="disabled page-item"><a class="page-link">Previous</a></li>
                            {% endif %}
                            {% for i in paginator.page_range %}
                            {% if page_obj.number == i %}
                            <li class="active page-item"><a class="page-link">{{ i }} <span class="sr-only">(current)</span></a></li>
                            {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                            {% endif %}
                            {% endfor %}
                            {% if page_obj.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% else %}
                            <li class="disabled page-item"><a class="page-link">Next</a></li>
                            {% endif %}
                        </ul>
                        {% endif %}
                    </div>
                </div>
                {% endblock main_content %}
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
    <script>


        new Vue({
            delimiters: ['[[', ']]'],
            el: '#root',
            data: {
                brand: 'Event CMS'
            }
        })
    </script>
    <script type="text/javascript">
        $(document).ready(function () {

            $(".create-book").modalForm({
                formURL: "{% url 'events:event_create' %}"
            });
            $(".update-book").each(function () {
                $(this).modalForm({formURL: $(this).data('id')});
              });
            

        });
    </script>
</body>

</html>

templates/login.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
</head>

<body>
    <div class="container h-100 justify-content-center align-items-center">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-md-6">
                <div class="form-group">
                    <form method="POST" action="{% url 'events:login' %}">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button class="btn btn-success" type='submit' title="login">Login</button>
                    </form>
                    <div class="custom-control custom-checkbox">
                        <input id="customCheck1" type="checkbox" checked class="custom-control-input">
                        <label for="customCheck1" class="custom-control-label">Remember Me</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>
<style>
    html,
    body {
        margin: 0;
        padding: 0;
        height: 100%;
        width: 100%;
    }
    .form-group{
        padding: 40px;
        box-shadow: 0px 0px 12px .2px lightgray;
    }
</style>